PriutZaKucheta/Controllers/RequestDogsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DogShelter.Entities;
using PriutZaKucheta.Data;

namespace DogShelter.Controllers
{
    public class RequestDogsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public RequestDogsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: RequestDogs
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.RequestDogs.Include(r => r.Adoptive).Include(r => r.Status);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: RequestDogs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var requestDog = await _context.RequestDogs
                .Include(r => r.Adoptive)
                .Include(r => r.Status)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (requestDog == null)
            {
                return NotFound();
            }

            return View(requestDog);
        }

        // GET: RequestDogs/Create
        public IActionResult Create()
        {
            ViewData["AdoptiveId"] = new SelectList(_context.Adoptives, "Id", "FirstName");
            ViewData["StatusId"] = new SelectList(_context.Statuses, "Id", "Id");
            return View();
        }

        // POST: RequestDogs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,DogId,AdoptiveId,CreatedOn,DateOfAdoption,StatusId")] RequestDog requestDog)
        {
            if (ModelState.IsValid)
            {
                _context.Add(requestDog);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AdoptiveId"] = new SelectList(_context.Adoptives, "Id", "FirstName", requestDog.AdoptiveId);
            ViewData["StatusId"] = new SelectList(_context.Statuses, "Id", "Id", requestDog.StatusId);
            return View(requestDog);
        }

        // GET: RequestDogs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var requestDog = await _context.RequestDogs.FindAsync(id);
            if (requestDog == null)
            {
                return NotFound();
            }
            ViewData["AdoptiveId"] = new SelectList(_context.Adoptives, "Id", "FirstName", requestDog.AdoptiveId);
            ViewData["StatusId"] = new SelectList(_context.Statuses, "Id", "Id", requestDog.StatusId);
            return View(requestDog);
        }

        // POST: RequestDogs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,DogId,AdoptiveId,CreatedOn,DateOfAdoption,StatusId")] RequestDog requestDog)
        {
            if (id != requestDog.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(requestDog);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RequestDogExists(requestDog.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AdoptiveId"] = new SelectList(_context.Adoptives, "Id", "FirstName", requestDog.AdoptiveId);
            ViewData["StatusId"] = new SelectList(_context.Statuses, "Id", "Id", requestDog.StatusId);
            return View(requestDog);
        }

        // GET: RequestDogs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var requestDog = await _context.RequestDogs
                .Include(r => r.Adoptive)
                .Include(r => r.Status)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (requestDog == null)
            {
                return NotFound();
            }

            return View(requestDog);
        }

        // POST: RequestDogs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var requestDog = await _context.RequestDogs.FindAsync(id);
            _context.RequestDogs.Remove(requestDog);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RequestDogExists(int id)
        {
            return _context.RequestDogs.Any(e => e.Id == id);
        }
    }
}

PriutZaKucheta/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PriutZaKucheta</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-success border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PriutZaKucheta</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if ((this.User.Identity.IsAuthenticated) && (this.User.IsInRole("Employee")))
                        {
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="RequestDogs" asp-action="Index">All Requests</a>
                    </li>}
                        @if ((this.User.Identity.IsAuthenticated) && (this.User.IsInRole("Administrator")))
                        {
                    <li class=" nav-item active">
                        <div class=" dropdown show">
                            <a class=" nav-link active dropdown-toggle" href="#"
                               id=" dropdownMenuLink"
                               data-toggle="dropdown"
                               aria-haspopup="true"
                               aria-expanded="false">
                                Employees
                            </a>
                            <div class=" dropdown-menu" aria-labelledby="dropdownMenuLink">
                                <a class=" dropdown-item" href="/Employees/Index">All</a>
                                <a class=" dropdown-item" href="/Employees/Create">Add</a>
                            </div>
                        </div>
                    </li>
                                    <li class=" nav-item active">
                                        <div class=" dropdown show">
                                            <a class=" nav-link active dropdown-toggle" href="#"
                                               id=" dropdownMenuLink"
                                               data-toggle="dropdown"
                                               aria-haspopup="true"
                                               aria-expanded="false">
                                                Places
                                            </a>
                                            <div class=" dropdown-menu" aria-labelledby="dropdownMenuLink">
                                                <a class=" dropdown-item" href="/Places/Index">All</a>
                                                <a class=" dropdown-item" href="/Places/Create">Add</a>
                                            </div>
                                        </div>
                                    </li>
                                                    <li class=" nav-item active">
                                                        <div class=" dropdown show">
                                                            <a class=" nav-link active dropdown-toggle" href="#"
                                                               id=" dropdownMenuLink"
                                                               data-toggle="dropdown"
                                                               aria-haspopup="true"
                                                               aria-expanded="false">
                                                                Dogs
                                                            </a>
                                                            <div class=" dropdown-menu" aria-labelledby="dropdownMenuLink">
                                                                <a class=" dropdown-item" href="/Dogs/Index">All</a>
                                                                <a class=" dropdown-item" href="/Dogs/Create">Add</a>
                                                            </div>
                                                        </div>
                                                    </li>}
                        @if ((this.User.Identity.IsAuthenticated) && (this.User.IsInRole("Adoptive")))
                        {
                    <li class=" nav-item active">
                        <div class=" dropdown show">
                            <a class=" nav-link active dropdown-toggle" href="#"
                               id=" dropdownMenuLink"
                               data-toggle="dropdown"
                               aria-haspopup="true"
                               aria-expanded="false">
                                Adopt
                            </a>
                            <div class=" dropdown-menu" aria-labelledby="dropdownMenuLink">
                                <a class=" dropdown-item" href="/RequestDogs/Index">My Requests</a>
                                <a class=" dropdown-item" href="/RequestDogs/Create">Add Request</a>
                            </div>
                        </div>
                    </li>}
                    </ul>
                            <partial name="_LoginPartial" />
                                </div>
                                </div>
                                </nav>
                           </header>
            <div class="container">
            <main role="main" class="pb-3">
            @RenderBody()
           </main>
         </div>

         <footer class="border-top footer text-muted">
          <div class="container">
            &copy; 2022 - PriutZaKucheta - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
         </div>
     </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>